comment_width = 100
format_code_in_doc_comments = true
format_strings = true
wrap_comments = true

# smoelius: Formatting with style edition 2021 makes incorporating Anchor source easier.
style_edition = "2021"
